config/routes.rb
Rails.application.routes.draw do
  root 'books#index'

  resources :books, only: [:index, :show, :new, :create] do
    resources :reviews, only: [:index, :new, :create]
  end

end

app/models/book.rb
class Book < ActiveRecord::Base
  has_many :reviews

  validates :title, presence: true
  validates :author, presence: true
  validates :isbn, presence: true
  validates :genre, presence: true
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :book
  
  validates :body, presence: true
  validates :rating, presence: true
  validates :rating, inclusion: { in: 0..100 }, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
   if @book.save
     flash[:notice] = "Book added"
     redirect_to '/'
   else
     flash[:error] = @book.errors.full_messages.join(". ")
     render :new
   end
  end

  def show
    @book = Book.find(params[:id])
    @review = Review.new
    @reviews = Review.where(book_id: params[:id])
  end

  protected
  def book_params
    params.require(:book).permit(:title, :author, :isbn, :genre)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @review = Review.new
    @book = Book.find(params[:book_id])
  end

  def create
    @review = Review.new(review_params)
    @book = Book.find(params[:book_id])
    @review.book = @book

    if @review.save
      flash[:notice] = 'Review submitted'
      redirect_to book_path(params[:book_id])
    else
      flash[:notice] = 'Missing content'
      redirect_to new_book_review_path(params[:book_id])
    end
  end

  protected
    def review_params
      params.require(:review).permit(:body, :rating, :book_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/books/index.html.erb
<h1> Book List </h1>
<ul>
  <% @books.each do |book| %>
    <li><%= link_to book.title, book %></li>
  <% end %>
</ul>

<%= link_to "Add Book", new_book_path %>

app/views/books/new.html.erb
<h1> Add Book </h1>
<%= form_for @book do |f| %>

<%= f.label :title %>
<%= f.text_field :title %>

<%= f.label :author %>
<%= f.text_field :author %>

<%= f.label :isbn %>
<%= f.text_field :isbn %>

<%= f.label :genre %>
<%= f.text_field :genre %>

<%= f.submit "Add Book", class: "button" %>
<% end %>

app/views/books/show.html.erb
<h1><%= @book.title %></h1>
<h4><%= @book.author %></h4>
<h6><%= @book.isbn %></h6>
<h6><%= @book.genre %></h6>

<h1> Reviews </h1>
<%= link_to "Write Review", new_book_review_path(@book) %>

<div class="review">
<% @reviews.each do |review| %>
<p>  Rating: <%= review.rating %> </p>
  <p> <%= review.body %><p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BookReviews</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%- flash.each do |key, value| -%>
      <div class="flash flash-<%= key %>">
        <%= value %>
      </div>
    <%- end -%>
<%= yield %>

</body>
</html>

app/views/reviews/new.html.erb
<h2> Review for <%= @book.title %> </h2>
<p>
<%= form_for [@book, @review] do |f| %>

<%= f.label :body %>
<%= f.text_field :body %>

<%= f.label :rating %>
<%= f.text_field :rating %>

<%= f.submit "Add Review", class: "button" %>
<% end %>
</p>